name: Build and Install .NET Framework
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET Framework
        run: |
          # Download .NET Framework installer
          Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2203306 -OutFile dotnet-framework-installer.exe

          # Install .NET Framework
          Start-Process -Wait -FilePath dotnet-framework-installer.exe -ArgumentList "/q"

          # Optional: Verify installation
          Get-WindowsFeature -Name NET-Framework-Core

      - name: Build application
        run: |
          # Navigate to the project directory
          cd .

          # Restore dependencies
          dotnet restore

          # Build the application
          dotnet build

      # Add additional steps for testing, publishing, etc.
